### PR TITLE
Add support for ImageElements  -> Parse images

### PR DESCRIPTION
**Pull request by ic-xu**
The images in the PDF were lost after parsing before. Now RAG needs to use images, so I added the image extraction function.

image

### CODE REVIEW

**Comment by Filimoa** [comment]
Thanks for the PR - this looks awesome! I will look a take a deeper look into this asap

**Comment by ic-xu** [comment]
Okay, if you have any needs, please communicate in time. I will be happy to communicate with you.

**Comment by Filimoa** [comment]
PdfMiner looks good - I changed the image schema to encode the image data in base64 str to allow for easy serialization.  We also added a mime type. Finally added a test - that looks good.

Looks like the pymupdf implementation is failing for me.

```python
import openparse

basic_doc_path = "/Users/sergey/Downloads/pdf-with-image.pdf"
pdf_obj = openparse.Pdf(basic_doc_path)
parsed_basic_doc = ingest(pdf_obj)
```
Returns
```
ValidationError: 1 validation error for Bbox
  Value error, y1 must be greater than y0 [type=value_error, input_value={'x0': 72.0, 'y0': 719.54...0, 'page_height': 792.0}, input_type=dict]
    For further information visit https://errors.pydantic.dev/2.9/v/value_error
```

I noticed you flipped the coordinates? Maybe why?
```python
fy0 = page.rect.height - node["bbox"][1]
fy1 = page.rect.height - node["bbox"][3]
```

To be honest, I'm not even sure how important it is to have this implemented for pymupdf because those documents are already OCRd and not sure how that affects this?

**Comment by Filimoa** [comment]
You can see the changes in the "parse-images-pdf-miner" branch - I can't seem to figure out how to merge it into this

**Comment by ic-xu** [comment]
> PdfMiner looks good - I changed the image schema to encode the image data in base64 str to allow for easy serialization. We also added a mime type. Finally added a test - that looks good.
> 
> Looks like the pymupdf implementation is failing for me.
> 
> ```python
> import openparse
> 
> basic_doc_path = "/Users/sergey/Downloads/pdf-with-image.pdf"
> pdf_obj = openparse.Pdf(basic_doc_path)
> parsed_basic_doc = ingest(pdf_obj)
> ```
> 
> Returns
> 
> ```
> ValidationError: 1 validation error for Bbox
>   Value error, y1 must be greater than y0 [type=value_error, input_value={'x0': 72.0, 'y0': 719.54...0, 'page_height': 792.0}, input_type=dict]
>     For further information visit https://errors.pydantic.dev/2.9/v/value_error
> ```
> 
> I noticed you flipped the coordinates? Maybe why?
> 
> ```python
> fy0 = page.rect.height - node["bbox"][1]
> fy1 = page.rect.height - node["bbox"][3]
> ```
> 
> To be honest, I'm not even sure how important it is to have this implemented for pymupdf because those documents are already OCRd and not sure how that affects this?

Indeed, for pymupdf, if the image has already been OCRed, then there is no need to parse the image anymore. However, I thought you would process the OCR in the process later, and only parse text in the text.

**Comment by ic-xu** [comment]
How about this, I'll submit the image parsing part for pdfminer first. As for pymupdf, I'll keep it as it is, without adding an image parsing module. Is that okay?

**Comment by Filimoa** [comment]
Sounds good!

**Pull request merged**
